### ISSUE TITLE
logbook-kai v23.4.1 での問題について

### ISSUE THREAD

**Issue by Re-ga** [rsky/logbook-kai-plugins#4]
いつも便利なプラグインを使わせていただきありがとうございます。

先日公開された logbook-kai v23.4.1にアップデートした際に、
logbook-kaiのその他タブ内に「戦果チャート」の項目が表示されなくなってしまいました。

こちらのローカルで
jre-x64 ビルド1.8.0.371-b11と v23.3.2の組み合わせでは動作しており
「戦果チャート」の項目が表示がされています。

対応をご検討いただければ幸いです。

**Comment by rsky** [comment]
@Re-ga issueに気づくのが大変遅くなってしまい、申し訳ありません。ライブラリをビルドし直してみました。これでいかがでしょうか？
https://github.com/rsky/logbook-kai-plugins/releases/tag/rankingchart-1.2.4

**Comment by Re-ga** [comment]
ご対応いただき感謝いたします。こちら無事に動作しております。
プラグインの読み込みも早くなったように感じます。
本当にありがとうございました。

季節の変わり目ですので、どうぞご自愛ください。
